name: "Google Spreadsheet Synchronizer"
description: "Sync GitHub Project Issues and/or PRs to a Google Spreadsheet"
branding:
  icon: "bar-chart-2"
  color: "green"
inputs:
  google-api-service-account-credentials:
    description: " Google service account credentials (JSON)"
    required: true
  document-id:
    description: "ID of your Google Spreadsheet "
    required: true
  sheet-name:
    description: "name of the sheet to export to"
    required: true
  mode:
    description: "sync mode to use"
    required: false
runs:
  using: "node16"
  main: "dist/index.js"
